# Sentiment Analysis for product rating



Importing the necessary Libraries to implement Sentiment Analysis

In [1]:
import nltk
import numpy as np

import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
import re
nltk.download('stopwords')
nltk.download('wordnet')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True








Importing pandas to read CSV file (Dataset) from the computer.

Also the display size of the text in the table is increased using 'set_option('display.max_colwidth',200)' in pandas library

In [2]:
import pandas as pd
pd.set_option('display.max_colwidth',200)
df=pd.read_csv(r"C:\Users\Dell\Desktop\GrammarandProductReviews.csv",encoding='UTF-8',sep=',')

# df.drop(['id','title'],axis='columns',inplace=True)
df.head()

rating  \
0       5   
1       5   
2       5   
3       1   
4       1   

                                                                                                                                                                                                   reviews  
0  i love this album. it's very good. more to the hip hop side than her current pop sound.. SO HYPE! i listen to this everyday at the gym! i give it 5star rating all the way. her metaphors are just c...  
1                                                                                                                                           Good flavor. This review was collected as part of a promotion.  
2                                                                                                                                                                                             Good flavor.  
3  I read through the reviews on here before looking in to buying one of the couples lubricants, and was ultimately disappointed that it didn't even live up to the reviews I had read. For starters, n...  
4                                                                     My husband bought this gel for us. The gel caused irritation and it felt like it was burning my skin. I wouldn't recommend this gel.

# Preprocessing
The columns in Dataframe are converted into integer and string datatype.
also the text in the review column are converted into lower cases because our model can predict the word 'THE' an 'the' as different entites


In [3]:
df.reviews = df.reviews.astype(str) 
df.rating = df.rating.astype(int) 
df.reviews = df.reviews.apply(lambda x: x.lower())
df.head()

rating  \
0       5   
1       5   
2       5   
3       1   
4       1   

                                                                                                                                                                                                   reviews  
0  i love this album. it's very good. more to the hip hop side than her current pop sound.. so hype! i listen to this everyday at the gym! i give it 5star rating all the way. her metaphors are just c...  
1                                                                                                                                           good flavor. this review was collected as part of a promotion.  
2                                                                                                                                                                                             good flavor.  
3  i read through the reviews on here before looking in to buying one of the couples lubricants, and was ultimately disappointed that it didn't even live up to the reviews i had read. for starters, n...  
4                                                                     my husband bought this gel for us. the gel caused irritation and it felt like it was burning my skin. i wouldn't recommend this gel.

In [4]:
# df['char_length'] = df['reviews'].apply(lambda x: len(str(x)))

In [5]:
# sns.set()
# df['char_length'].hist()
# plt.show()


Using Regular Expression for correcting the word so that word redundancy can reduced

In [6]:
 def clean_text(text):
     text = text.lower()
     text = re.sub(r"what's", "what is ", text)
     text = re.sub(r"\'s", " ", text)
     text = re.sub(r"\'ve", " have ", text)
     text = re.sub(r"can't", "cannot ", text)
     text = re.sub(r"n't", " not ", text)
     text = re.sub(r"i'm", "i am ", text)
     text = re.sub(r"\'re", " are ", text)
     text = re.sub(r"\'d", " would ", text)
     text = re.sub(r"\'ll", " will ", text)
     text = re.sub(r"\'scuse", " excuse ", text)
     text = re.sub('\W', ' ', text)
     text = re.sub('\s+', ' ', text)
     text = text.strip(' ')
     return text

In [7]:
 df['reviews'] = df['reviews'].apply(lambda com : clean_text(com))

In [8]:
# df.head()

# Removing Punctuation 

In [9]:
import string
def remove_punctuations(txt):
    txt = "".join([c for c in txt if c not in string.punctuation])
    return txt

In [10]:
df['new_column'] = df['reviews'].apply(remove_punctuations)
df.head()

rating  \
0       5   
1       5   
2       5   
3       1   
4       1   

                                                                                                                                                                                                   reviews  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                                new_column  
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy  
1                                                                                                                                             good flavor this review was collected as part of a promotion  
2                                                                                                                                                                                              good flavor  
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...  
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel

# Removing Number 
Because the Number will not that helpul to reflect the sentiment / emotion 

In [11]:
df['new_cloumns'] = df['new_column'].str.replace('\d+', 'number') # to replace no. by ""
df.head()

rating  \
0       5   
1       5   
2       5   
3       1   
4       1   

                                                                                                                                                                                                   reviews  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                                new_column  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                               new_cloumns  
0     i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it numberstar rating all the way her metaphors are just crazy  
1                                                                                                                                             good flavor this review was collected as part of a promotion  
2                                                                                                                                                                                              good flavor  
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...  
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel

# Tokenization
we have to iterate through each and every word in the sentence of the dataset 

In [12]:
import re

def tokenize(txt):
    tokens = re.split('\W+' , txt)
    return tokens
df['tokenize']=df['new_cloumns'].apply(lambda x: tokenize(x.lower()))
df.head()

rating  \
0       5   
1       5   
2       5   
3       1   
4       1   

                                                                                                                                                                                                   reviews  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                                new_column  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                               new_cloumns  \
0     i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it numberstar rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                                  tokenize  
0  [i, l

# Removing Stopword 

In [13]:
import nltk
stopwords = nltk.corpus.stopwords.words('english')
stopwords[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [14]:
def remove_stopwords(txt_tokenized):
    txt_clean = [word for word in txt_tokenized if word not in stopwords]
    return txt_clean
df['sw']=df['tokenize'].apply(lambda x: remove_stopwords(x))

# Lemattization
Finds root word of the similar words which helps to reduce the computation of our model

In [15]:
from nltk.stem import WordNetLemmatizer
wn=WordNetLemmatizer()

In [16]:
def lemmatization(token_txt):
    text = [wn.lemmatize(word) for word in token_txt]
    
    return text

df['lemmatize']= df['sw'].apply(lambda x : lemmatization(x))
df.head()

rating  \
0       5   
1       5   
2       5   
3       1   
4       1   

                                                                                                                                                                                                   reviews  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                                new_column  \
0          i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it 5star rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                               new_cloumns  \
0     i love this album it very good more to the hip hop side than her current pop sound so hype i listen to this everyday at the gym i give it numberstar rating all the way her metaphors are just crazy   
1                                                                                                                                             good flavor this review was collected as part of a promotion   
2                                                                                                                                                                                              good flavor   
3  i read through the reviews on here before looking in to buying one of the couples lubricants and was ultimately disappointed that it did not even live up to the reviews i had read for starters nei...   
4                                                                       my husband bought this gel for us the gel caused irritation and it felt like it was burning my skin i would not recommend this gel   

                                                                                                                                                                                                  tokenize  \
0  [i, 

# Finding NA values in our huge dataset
we find those ones and fill them with the average value in the dataset i.e. rating 

In [17]:
df.columns[df.isna().any()]

Index([], dtype='object')

In [18]:
df.isna().sum()

rating         0
reviews        0
new_column     0
new_cloumns    0
tokenize       0
sw             0
lemmatize      0
dtype: int64

In [19]:
df.info() #provides info of null fields

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71044 entries, 0 to 71043
Data columns (total 7 columns):
rating         71044 non-null int32
reviews        71044 non-null object
new_column     71044 non-null object
new_cloumns    71044 non-null object
tokenize       71044 non-null object
sw             71044 non-null object
lemmatize      71044 non-null object
dtypes: int32(1), object(6)
memory usage: 3.5+ MB


In [20]:
df.rating = df.rating.fillna(df.rating.mean())

In [21]:
df.isna().sum()

rating         0
reviews        0
new_column     0
new_cloumns    0
tokenize       0
sw             0
lemmatize      0
dtype: int64

# Splitting Dataset for Training and Testing 

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.lemmatize,df.rating,test_size=0.3,random_state=1)

In [23]:
len(X_test)

21314

In [24]:
print(X_train)

21393                                                                                                                                                                    [great, combo, tostitos, chunky, salsa]
10375                                                                                              [love, keep, bathroom, always, quick, clean, especially, surprise, guest, review, collected, part, promotion]
47564                                                                                                                                                                                       [work, wonder, skin]
14738                                                                                                          [love, product, wonderful, best, ever, cannot, live, without, review, collected, part, promotion]
15488                                                                                                                                                         [work,

# Feature Extraction
generating matrix value of text Dataset using Countvectorizer then converting them into TFIDF (term frequency–inverse document frequency) 

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(analyzer = lemmatization)

training_data = cv.fit_transform(X_train)
training_data_toarray= training_data.toarray()
print(training_data_toarray)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
Xtrain_tfidf = tfidf_transformer.fit_transform(training_data)

In [27]:
Xtrain_tfidf.shape

(49730, 20295)

In [28]:
# print(Xtrain_tfidf.toarray())

# Implementing the Naive Bayes model and fitting the taining dataset 

In [29]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(Xtrain_tfidf, y_train)


# Testing the model

In [30]:
X_test_tf = cv.transform(X_test)
X_test_tfidf=tfidf_transformer.transform(X_test_tf)
predicted= clf.predict(X_test_tfidf)

In [31]:
# from sklearn import metrics
# from sklearn.metrics import accuracy_score
# target_names = ['1' , '2', '3', '4', '5']
# print("Accuracy:", accuracy_score(y_test, predicted))
# print(metrics.classification_report((y_test, predicted, target_names= y_test.target_names)),metrics.confusion_matrix(y_train, predicted))

# Precision
# Confusion matrix

In [32]:
from sklearn import metrics
print(metrics.classification_report(y_test, predicted)) #target nameko list banaune then yo code ma tagetnames= targetname list garne
# print(metrics.confusion_matrix((y_test, predicted))


             precision    recall  f1-score   support

          1       0.86      0.18      0.30      1089
          2       0.00      0.00      0.00       528
          3       0.50      0.00      0.00      1308
          4       0.41      0.03      0.06      4369
          5       0.67      0.99      0.80     14020

avg / total       0.60      0.67      0.56     21314



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
from sklearn.metrics import accuracy_score
print("Accuracy score: ", accuracy_score(y_test,predicted))

Accuracy score:  0.6696068311907666


In [34]:
print(metrics.confusion_matrix(y_test, predicted))

[[  196     0     0     6   887]
 [   23     0     0    17   488]
 [    6     0     2    98  1202]
 [    3     0     0   146  4220]
 [    1     0     2    89 13928]]


# Implementing the Naive Bayes model and fitting the taining dataset

In [35]:
# from sklearn.svm import SVC
# svc = SVC()
# svc.fit(Xtrain_tfidf, y_train)

In [36]:
predict = svc.predict(X_test_tfidf)

NameError: name 'svc' is not defined

# Precision And COnfusion Matrix

In [37]:
from sklearn import metrics
print(metrics.classification_report(y_test, predict))

NameError: name 'predict' is not defined

In [38]:
from sklearn.metrics import accuracy_score
print("Accuracy score: ", accuracy_score(y_test,predict))

NameError: name 'predict' is not defined

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
LR = LogisticRegression()
LR.fit(Xtrain_tfidf, y_train)
pred = LR.predict(X_test_tfidf)

In [41]:
from sklearn import metrics
print(metrics.classification_report(y_test, pred))

             precision    recall  f1-score   support

          1       0.70      0.60      0.64      1089
          2       0.28      0.02      0.04       528
          3       0.48      0.11      0.19      1308
          4       0.47      0.20      0.28      4369
          5       0.74      0.96      0.84     14020

avg / total       0.66      0.71      0.65     21314



# Testing the external input

In [42]:
# doc = ['This product so far has not disappointed', 'electronics product are bad']
# doc_counts = cv.transform(doc)
# doc_tfidf=tfidf_transformer.transform(doc_counts)
# predicted= clf.predict(doc_tfidf)


In [43]:
# for x in predicted:
#     print(x)

How it worked ?
Dataframe class provides a constructor to create Dataframe object by passing column names , index names & data in argument like this,
def __init__(self, data=None, index=None, columns=None, dtype=None,

In [44]:
import pandas as pd
dfObj = pd.DataFrame(columns=['User_ID', 'UserName', 'Action'])
print("Empty Dataframe ", dfObj, sep='\n')


Empty Dataframe 
Empty DataFrame
Columns: [User_ID, UserName, Action]
Index: []


In [45]:
dfObj.head()

Empty DataFrame
Columns: [User_ID, UserName, Action]
Index: []

In [46]:
dfObj = dfObj.append({'User_ID': 23, 'UserName': 'Riti', 'Action': 'Login'}, ignore_index=True)

In [47]:
dfObj.head()

User_ID UserName Action
0      23     Riti  Login

In [48]:
Doc = pd.DataFrame(columns=['testing'])

In [49]:
Doc = Doc.append({'testing':'Absolutely worthless - not silky and dim and uncomfortable' }, ignore_index=True)

In [50]:
Doc = Doc.append({'testing':'I had such high hopes for this dress and really wanted it to work for me. i initially ordered the petite small (my usual size) but i found this to be outrageously small. so small in fact that i could not zip it up! i reordered it in petite medium, which was just ok. overall, the top half was comfortable and fit nicely, but the bottom half had a very tight under layer and several somewhat cheap (net) over layers. imo, a major design flaw was the net over layer sewn directly into the zipper - it c' }, ignore_index=True)

In [51]:
Doc.head()

testing
0                                                                                                                                               Absolutely worthless - not silky and dim and uncomfortable
1  I had such high hopes for this dress and really wanted it to work for me. i initially ordered the petite small (my usual size) but i found this to be outrageously small. so small in fact that i co...

In [52]:
Doc.testing = Doc.testing.astype(str) 
 
Doc.testing = Doc.testing.apply(lambda x: x.lower())
Doc.head()

testing
0                                                                                                                                               absolutely worthless - not silky and dim and uncomfortable
1  i had such high hopes for this dress and really wanted it to work for me. i initially ordered the petite small (my usual size) but i found this to be outrageously small. so small in fact that i co...

In [53]:
import string
def remove_punctuations(txt):
    txt = "".join([c for c in txt if c not in string.punctuation])
    return txt



In [54]:
Doc['testing'] = Doc['testing'].apply(remove_punctuations)
Doc.head()

testing
0                                                                                                                                                absolutely worthless  not silky and dim and uncomfortable
1  i had such high hopes for this dress and really wanted it to work for me i initially ordered the petite small my usual size but i found this to be outrageously small so small in fact that i could ...

In [55]:
import re

def tokenize(txt):
    tokens = re.split('\W+' , txt)
    return tokens
Doc['testing']=Doc['testing'].apply(lambda x: tokenize(x.lower()))
Doc.head()

testing
0                                                                                                                                        [absolutely, worthless, not, silky, and, dim, and, uncomfortable]
1  [i, had, such, high, hopes, for, this, dress, and, really, wanted, it, to, work, for, me, i, initially, ordered, the, petite, small, my, usual, size, but, i, found, this, to, be, outrageously, sma...

In [56]:
import nltk
stopwords = nltk.corpus.stopwords.words('english')
stopwords[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [57]:
def remove_stopwords(txt_tokenized):
    txt_clean = [word for word in txt_tokenized if word not in stopwords]
    return txt_clean
Doc['testing']=Doc['testing'].apply(lambda x: remove_stopwords(x))
Doc.head()

testing
0                                                                                                                                                       [absolutely, worthless, silky, dim, uncomfortable]
1  [high, hopes, dress, really, wanted, work, initially, ordered, petite, small, usual, size, found, outrageously, small, small, fact, could, zip, reordered, petite, medium, ok, overall, top, half, c...

In [58]:
def lemmatization(token_txt):
    text = [wn.lemmatize(word) for word in token_txt]
    return text

Doc['testing']= Doc['testing'].apply(lambda x : lemmatization(x))
Doc.head()

testing
0                                                                                                                                                       [absolutely, worthless, silky, dim, uncomfortable]
1  [high, hope, dress, really, wanted, work, initially, ordered, petite, small, usual, size, found, outrageously, small, small, fact, could, zip, reordered, petite, medium, ok, overall, top, half, co...

In [59]:
doc_counts = cv.transform(Doc.testing)
doc_tfidf=tfidf_transformer.transform(doc_counts)
predicts= c.predict(doc_tfidf)


In [60]:
for x in predicts:
    print(x)

5
5
